### ISSUE TITLE
sonic snmpagent doesn't support mgmt (a.k.a eth0) in RFC1213-MIB ifTable

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-snmpagent#83]
**Description**

sonic-snmpagent doesn't support mgmt (eth0) in RFC1213-MIB ifTable, oid 1.3.6.1.2.1.2.2.

[init_sync_d_interface_tables](https://github.com/Azure/sonic-snmpagent/blob/master/src/sonic_ax_impl/mibs/__init__.py#L117) gets physical interfaces from CONFIG_DB, but doesn't get eth0.

**Comment by qiluo-msft** [comment]
Currently only support front panel interfaces and LAG interfaces, no support on mgmt, loopback, or vlan interfaces.
First how does the standard defined on these interfaces?
Second would you like to provide a PR if they are really required by standard?
We don't have it on priority since our management stack doesn't care about those interfaces.

**Comment by sunnogo** [comment]
I just created a new private oid... NOT a good approach.

**Comment by qiluo-msft** [comment]
Thanks for reporting this issue! It is on our TODO list and we are actively investigating.

**Comment by qiluo-msft** [comment]
Check our design https://github.com/Azure/SONiC/wiki/SONiC-SMMP-Design-on-Management-Ports and welcome any suggestion.
